### ISSUE TITLE
EPIC: as a big data 4 tourism user I want to have an easier data analysis tool in order to improve the quality of my services on top of the analysis that I can easily see through the platform.

### ISSUE THREAD

**Issue by sseppi** [idm-suedtirol/big-data-for-tourism#2]
- [x] the upload tool has to be simplified and prepared to upload the file where Apache NiFi can pick it up
- [x] an istance of Apache NiFi has to be instlaeed nd configured according on the decisions taken during the workshop
     - [x] create a GitHub repository for the Nifi project
     - [x] create a clean machine with 4 core and 8Gb of RAM #1 
     - [x] install and configure Apache NiFi
- [ ] the standard Kibana Dashboard has to be simplified according to the decision taken during the workshop.
     - [x] create a GitHub repository for the Kibana plugins project

**Comment by sseppi** [comment]
The whole system is in testing and there are still some bugs to be solved.
