### ISSUE TITLE
EPIC: As a BigData4Tourism member I want to have online the new simplified version of the Kibana Dashboard in order to access to be able to analyze the data also without a deep knowledge of Kibana.

### ISSUE THREAD

**Issue by sseppi** [idm-suedtirol/big-data-for-tourism#3]
Seacom and Patrick Puecher ended their work on the Elastic Search and on the data uploader and now the two components must be connected in order to import the data in Elastic Search. In order to do that it must be fullfilled the following points:
- [ ] setup a scp system (the uploader of Patrick Puecher must store the file to upload in a folder provided by Seacom);
- [x] a meeting must be organized where Patrick Puecher and Seacom present their work ad a first test roud will be implemented;
- [ ] test internally the whole system in order to find last bugs.

**Comment by sseppi** [comment]
At the meeting it could be useful to have also one of our developers in order to let them know how the entire architecture is configured?

**Comment by bertolla** [comment]
@sseppi 
When will the meeting be?

**Comment by sseppi** [comment]
@bertolla 
Probably the 8th of February, I'm waiting for the confirmation of the last person who has to attend to the meeting and then I'll do the invitation.

**Comment by bertolla** [comment]
@sseppi 
So there is nothing to do in this Sprint???
Back to Backlog??

**Comment by sseppi** [comment]
@sseppi  contact Seacom and P. Puecher to get the timeline of their activities and ask for the sourcecode

**Comment by LucaMiotto** [comment]
@sseppi moved to EPIC, please divide in separated issues.
